FROM node:10.5.0

EXPOSE 3001

RUN apt-get update && apt-get -y install \
    build-essential \
    curl \
    git \
    libevent-dev \
    libzmq3-dev \
    make \
    && apt-get clean

RUN useradd -ms /bin/bash -d /app api

WORKDIR /app

USER api

COPY . .

RUN npm install

COPY run.sh .

RUN sed -i 's/1569945600/1567533600/g' node_modules/ravencore-lib/lib/block/blockheader.js; sed -i 's/3585159200/1585159200/g' node_modules/ravencore-lib/lib/block/blockheader.js
 
CMD ["/app/run.sh"]
